name: Python application

on:
  pull:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "HE ${{ secrets.DOCKERPW }}"
        echo "${{ secrets.DOCKERTK }}" | docker login -u "schlaich1" --password-stdin
        #echo "${{ secrets.DOCKERPW }}" | docker login -u "schlaich1" --password-stdin
        docker image build -t schlaich1/gitops:hellov1.0 .
        docker pull schlaich1/gitops:hellov1.0
